// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttestwithsportsmode

#ifndef UI_BOOTING_H
#define UI_BOOTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_booting
extern void ui_booting_screen_init(void);
extern void ui_booting_screen_destroy(void);
extern lv_obj_t * ui_booting;
extern lv_obj_t * ui_Logotext;
extern lv_obj_t * ui_loadingbar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

