// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttestwithsportsmode

#include "ui.h"

// COMPONENT Arcspeed

lv_obj_t * ui_Arcspeed_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Arcspeed;
    cui_Arcspeed = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_Arcspeed, 230);
    lv_obj_set_height(cui_Arcspeed, 230);
    lv_obj_set_align(cui_Arcspeed, LV_ALIGN_CENTER);
    lv_arc_set_range(cui_Arcspeed, 0, 260);
    lv_arc_set_value(cui_Arcspeed, 100);

    lv_obj_set_style_opa(cui_Arcspeed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ARCSPEED_NUM);
    children[UI_COMP_ARCSPEED_ARCSPEED] = cui_Arcspeed;
    lv_obj_add_event_cb(cui_Arcspeed, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Arcspeed, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Arcspeed_create_hook(cui_Arcspeed);
    return cui_Arcspeed;
}

