// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttestwithsportsmode

#include "ui.h"

lv_obj_t * ui_normalday = NULL;
lv_obj_t * ui_Arcspeed = NULL;
lv_obj_t * ui_speedlabel = NULL;
lv_obj_t * ui_kmhtext = NULL;
lv_obj_t * ui_autoholdindicator = NULL;
lv_obj_t * ui_Arccoolant = NULL;
lv_obj_t * ui_SCCsettext = NULL;
lv_obj_t * ui_SCCsetspeedlabel = NULL;
lv_obj_t * ui_SCCkmhtext = NULL;
lv_obj_t * ui_SCCArcON = NULL;
lv_obj_t * ui_coolantimg = NULL;
lv_obj_t * ui_SCCimg = NULL;
lv_obj_t * ui_gearlabel = NULL;
// event funtions

// build funtions

void ui_normalday_screen_init(void)
{
    ui_normalday = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_normalday, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arcspeed = ui_Arcspeed_create(ui_normalday);
    lv_obj_set_x(ui_Arcspeed, 0);
    lv_obj_set_y(ui_Arcspeed, 0);

    ui_speedlabel = lv_label_create(ui_normalday);
    lv_obj_set_width(ui_speedlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_speedlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedlabel, "100");
    lv_obj_set_style_text_font(ui_speedlabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmhtext = lv_label_create(ui_normalday);
    lv_obj_set_width(ui_kmhtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmhtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmhtext, 0);
    lv_obj_set_y(ui_kmhtext, 40);
    lv_obj_set_align(ui_kmhtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmhtext, "Km/h");

    ui_autoholdindicator = lv_label_create(ui_normalday);
    lv_obj_set_width(ui_autoholdindicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autoholdindicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autoholdindicator, 65);
    lv_obj_set_y(ui_autoholdindicator, 0);
    lv_obj_set_align(ui_autoholdindicator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autoholdindicator, "AUTO\nHOLD");
    lv_obj_set_style_text_font(ui_autoholdindicator, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arccoolant = lv_arc_create(ui_normalday);
    lv_obj_set_width(ui_Arccoolant, 230);
    lv_obj_set_height(ui_Arccoolant, 230);
    lv_obj_set_align(ui_Arccoolant, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arccoolant, 0, 160);
    lv_arc_set_value(ui_Arccoolant, 80);
    lv_arc_set_bg_angles(ui_Arccoolant, 60, 120);
    lv_arc_set_mode(ui_Arccoolant, LV_ARC_MODE_REVERSE);

    lv_obj_set_style_arc_color(ui_Arccoolant, lv_color_hex(0x2BCC30), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arccoolant, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Arccoolant, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SCCsettext = lv_label_create(ui_normalday);
    lv_obj_set_width(ui_SCCsettext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SCCsettext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SCCsettext, 0);
    lv_obj_set_y(ui_SCCsettext, -85);
    lv_obj_set_align(ui_SCCsettext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SCCsettext, "SET");
    lv_obj_add_flag(ui_SCCsettext, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_SCCsettext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SCCsetspeedlabel = lv_label_create(ui_normalday);
    lv_obj_set_width(ui_SCCsetspeedlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SCCsetspeedlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SCCsetspeedlabel, 0);
    lv_obj_set_y(ui_SCCsetspeedlabel, -65);
    lv_obj_set_align(ui_SCCsetspeedlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SCCsetspeedlabel, "120");
    lv_obj_add_flag(ui_SCCsetspeedlabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_SCCsetspeedlabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SCCkmhtext = lv_label_create(ui_normalday);
    lv_obj_set_width(ui_SCCkmhtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SCCkmhtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SCCkmhtext, 35);
    lv_obj_set_y(ui_SCCkmhtext, -65);
    lv_obj_set_align(ui_SCCkmhtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SCCkmhtext, "Km/h");
    lv_obj_add_flag(ui_SCCkmhtext, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_SCCkmhtext, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SCCArcON = lv_arc_create(ui_normalday);
    lv_obj_set_width(ui_SCCArcON, 230);
    lv_obj_set_height(ui_SCCArcON, 230);
    lv_obj_set_align(ui_SCCArcON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SCCArcON, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_range(ui_SCCArcON, 0, 260);
    lv_arc_set_value(ui_SCCArcON, 120);
    lv_obj_set_style_opa(ui_SCCArcON, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SCCArcON, lv_color_hex(0x00FF03), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SCCArcON, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SCCArcON, lv_color_hex(0x6BFF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SCCArcON, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_coolantimg = lv_img_create(ui_normalday);
    lv_obj_set_width(ui_coolantimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolantimg, 0);
    lv_obj_set_y(ui_coolantimg, 88);
    lv_obj_set_align(ui_coolantimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coolantimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_coolantimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SCCimg = lv_img_create(ui_normalday);
    lv_obj_set_width(ui_SCCimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SCCimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SCCimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SCCimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SCCimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gearlabel = lv_label_create(ui_normalday);
    lv_obj_set_width(ui_gearlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gearlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gearlabel, 0);
    lv_obj_set_y(ui_gearlabel, -80);
    lv_obj_set_align(ui_gearlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gearlabel, "D");
    lv_obj_set_style_text_font(ui_gearlabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_normalday_screen_destroy(void)
{
    if(ui_normalday) lv_obj_del(ui_normalday);

    // NULL screen variables
    ui_normalday = NULL;
    ui_Arcspeed = NULL;
    ui_speedlabel = NULL;
    ui_kmhtext = NULL;
    ui_autoholdindicator = NULL;
    ui_Arccoolant = NULL;
    ui_SCCsettext = NULL;
    ui_SCCsetspeedlabel = NULL;
    ui_SCCkmhtext = NULL;
    ui_SCCArcON = NULL;
    ui_coolantimg = NULL;
    ui_SCCimg = NULL;
    ui_gearlabel = NULL;

}
