// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttestwithsportsmode

#ifndef UI_NORMALDAY_H
#define UI_NORMALDAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_normalday
extern void ui_normalday_screen_init(void);
extern void ui_normalday_screen_destroy(void);
extern lv_obj_t * ui_normalday;
extern lv_obj_t * ui_Arcspeed;
extern lv_obj_t * ui_speedlabel;
extern lv_obj_t * ui_kmhtext;
extern lv_obj_t * ui_autoholdindicator;
extern lv_obj_t * ui_Arccoolant;
extern lv_obj_t * ui_SCCsettext;
extern lv_obj_t * ui_SCCsetspeedlabel;
extern lv_obj_t * ui_SCCkmhtext;
extern lv_obj_t * ui_SCCArcON;
extern lv_obj_t * ui_coolantimg;
extern lv_obj_t * ui_SCCimg;
extern lv_obj_t * ui_gearlabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

