// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttestwithsportsmode

#include "ui.h"

lv_obj_t * ui_sportsmode = NULL;
lv_obj_t * ui_sptRPMgauge = NULL;
lv_obj_t * ui_sptspeedlabel = NULL;
lv_obj_t * ui_sptkmhtext = NULL;
lv_obj_t * ui_sptcoolantgauge = NULL;
lv_obj_t * ui_sptrpmtext = NULL;
lv_obj_t * ui_sptcoolanttext = NULL;
lv_obj_t * ui_sptautoholdindicator = NULL;
lv_obj_t * ui_sptgearlabel = NULL;
lv_obj_t * ui_sptSCCsettext = NULL;
lv_obj_t * ui_sptSCCsetspeedlabel = NULL;
lv_obj_t * ui_sptSCCkmhtext = NULL;
lv_obj_t * ui_sptSCCimg = NULL;
// event funtions

// build funtions

void ui_sportsmode_screen_init(void)
{
    ui_sportsmode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sportsmode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sportsmode, lv_color_hex(0x1E0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sportsmode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_sportsmode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_sportsmode, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_sportsmode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_sportsmode, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptRPMgauge = lv_arc_create(ui_sportsmode);
    lv_obj_set_width(ui_sptRPMgauge, 240);
    lv_obj_set_height(ui_sptRPMgauge, 240);
    lv_obj_set_align(ui_sptRPMgauge, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_sptRPMgauge, 0, 8000);
    lv_arc_set_value(ui_sptRPMgauge, 3000);
    lv_arc_set_bg_angles(ui_sptRPMgauge, 90, 0);
    lv_obj_set_style_shadow_color(ui_sptRPMgauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_sptRPMgauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_sptRPMgauge, lv_color_hex(0x5D0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_sptRPMgauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_sptRPMgauge, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_sptRPMgauge, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_sptRPMgauge, lv_color_hex(0xD93737), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_sptRPMgauge, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_sptRPMgauge, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_sptRPMgauge, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_sptRPMgauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_sptspeedlabel = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptspeedlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptspeedlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sptspeedlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptspeedlabel, "100");
    lv_obj_set_style_text_color(ui_sptspeedlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptspeedlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_sptspeedlabel, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sptspeedlabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptkmhtext = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptkmhtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptkmhtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sptkmhtext, 0);
    lv_obj_set_y(ui_sptkmhtext, 45);
    lv_obj_set_align(ui_sptkmhtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptkmhtext, "Km/h");
    lv_obj_set_style_text_color(ui_sptkmhtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptkmhtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sptkmhtext, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptcoolantgauge = lv_arc_create(ui_sportsmode);
    lv_obj_set_width(ui_sptcoolantgauge, 190);
    lv_obj_set_height(ui_sptcoolantgauge, 190);
    lv_obj_set_align(ui_sptcoolantgauge, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_sptcoolantgauge, 0, 160);
    lv_arc_set_value(ui_sptcoolantgauge, 90);
    lv_arc_set_bg_angles(ui_sptcoolantgauge, 90, 180);
    lv_obj_set_style_arc_color(ui_sptcoolantgauge, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_sptcoolantgauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_sptcoolantgauge, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_sptcoolantgauge, lv_color_hex(0xFFAD40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_sptcoolantgauge, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_sptcoolantgauge, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_sptcoolantgauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_sptrpmtext = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptrpmtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptrpmtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sptrpmtext, 20);
    lv_obj_set_y(ui_sptrpmtext, 105);
    lv_obj_set_align(ui_sptrpmtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptrpmtext, "RPM");
    lv_obj_set_style_text_color(ui_sptrpmtext, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptrpmtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptcoolanttext = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptcoolanttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptcoolanttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sptcoolanttext, 30);
    lv_obj_set_y(ui_sptcoolanttext, 90);
    lv_obj_set_align(ui_sptcoolanttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptcoolanttext, "coolant");
    lv_obj_set_style_text_color(ui_sptcoolanttext, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptcoolanttext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptautoholdindicator = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptautoholdindicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptautoholdindicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sptautoholdindicator, 70);
    lv_obj_set_y(ui_sptautoholdindicator, 0);
    lv_obj_set_align(ui_sptautoholdindicator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptautoholdindicator, "AUTO\nHOLD");
    lv_obj_set_style_text_color(ui_sptautoholdindicator, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptautoholdindicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sptautoholdindicator, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptgearlabel = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptgearlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptgearlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sptgearlabel, 70);
    lv_obj_set_y(ui_sptgearlabel, 45);
    lv_obj_set_align(ui_sptgearlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptgearlabel, "D");
    lv_obj_set_style_text_color(ui_sptgearlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptgearlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sptgearlabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptSCCsettext = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptSCCsettext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptSCCsettext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sptSCCsettext, 0);
    lv_obj_set_y(ui_sptSCCsettext, -91);
    lv_obj_set_align(ui_sptSCCsettext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptSCCsettext, "SET");
    lv_obj_set_style_text_color(ui_sptSCCsettext, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptSCCsettext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sptSCCsettext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptSCCsetspeedlabel = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptSCCsetspeedlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptSCCsetspeedlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sptSCCsetspeedlabel, 0);
    lv_obj_set_y(ui_sptSCCsetspeedlabel, -72);
    lv_obj_set_align(ui_sptSCCsetspeedlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptSCCsetspeedlabel, "120");
    lv_obj_set_style_text_color(ui_sptSCCsetspeedlabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptSCCsetspeedlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sptSCCsetspeedlabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptSCCkmhtext = lv_label_create(ui_sportsmode);
    lv_obj_set_width(ui_sptSCCkmhtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sptSCCkmhtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sptSCCkmhtext, 35);
    lv_obj_set_y(ui_sptSCCkmhtext, -72);
    lv_obj_set_align(ui_sptSCCkmhtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sptSCCkmhtext, "Km/h");
    lv_obj_set_style_text_color(ui_sptSCCkmhtext, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sptSCCkmhtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sptSCCkmhtext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sptSCCimg = lv_img_create(ui_sportsmode);
    lv_obj_set_width(ui_sptSCCimg, 117);
    lv_obj_set_height(ui_sptSCCimg, 28);
    lv_obj_set_x(ui_sptSCCimg, 0);
    lv_obj_set_y(ui_sptSCCimg, -40);
    lv_obj_set_align(ui_sptSCCimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sptSCCimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sptSCCimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_sportsmode_screen_destroy(void)
{
    if(ui_sportsmode) lv_obj_del(ui_sportsmode);

    // NULL screen variables
    ui_sportsmode = NULL;
    ui_sptRPMgauge = NULL;
    ui_sptspeedlabel = NULL;
    ui_sptkmhtext = NULL;
    ui_sptcoolantgauge = NULL;
    ui_sptrpmtext = NULL;
    ui_sptcoolanttext = NULL;
    ui_sptautoholdindicator = NULL;
    ui_sptgearlabel = NULL;
    ui_sptSCCsettext = NULL;
    ui_sptSCCsetspeedlabel = NULL;
    ui_sptSCCkmhtext = NULL;
    ui_sptSCCimg = NULL;

}
