// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttestwithsportsmode

#ifndef UI_SPORTSMODE_H
#define UI_SPORTSMODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sportsmode
extern void ui_sportsmode_screen_init(void);
extern void ui_sportsmode_screen_destroy(void);
extern lv_obj_t * ui_sportsmode;
extern lv_obj_t * ui_sptRPMgauge;
extern lv_obj_t * ui_sptspeedlabel;
extern lv_obj_t * ui_sptkmhtext;
extern lv_obj_t * ui_sptcoolantgauge;
extern lv_obj_t * ui_sptrpmtext;
extern lv_obj_t * ui_sptcoolanttext;
extern lv_obj_t * ui_sptautoholdindicator;
extern lv_obj_t * ui_sptgearlabel;
extern lv_obj_t * ui_sptSCCsettext;
extern lv_obj_t * ui_sptSCCsetspeedlabel;
extern lv_obj_t * ui_sptSCCkmhtext;
extern lv_obj_t * ui_sptSCCimg;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

