// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttest

#include "ui.h"

lv_obj_t * ui_booting = NULL;
lv_obj_t * ui_Logotext = NULL;
lv_obj_t * ui_loadingbar = NULL;
// event funtions

// build funtions

void ui_booting_screen_init(void)
{
    ui_booting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_booting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Logotext = lv_label_create(ui_booting);
    lv_obj_set_width(ui_Logotext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Logotext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Logotext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Logotext, "GENESIS");
    lv_obj_set_style_text_font(ui_Logotext, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadingbar = lv_bar_create(ui_booting);
    lv_bar_set_value(ui_loadingbar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_loadingbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_loadingbar, 130);
    lv_obj_set_height(ui_loadingbar, 10);
    lv_obj_set_x(ui_loadingbar, 0);
    lv_obj_set_y(ui_loadingbar, 30);
    lv_obj_set_align(ui_loadingbar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_loadingbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_loadingbar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_loadingbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_loadingbar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_loadingbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_loadingbar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}

void ui_booting_screen_destroy(void)
{
    if(ui_booting) lv_obj_del(ui_booting);

    // NULL screen variables
    ui_booting = NULL;
    ui_Logotext = NULL;
    ui_loadingbar = NULL;

}
