// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttest

#ifndef _UI_COMP_ARCSPEED_H
#define _UI_COMP_ARCSPEED_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Arcspeed
#define UI_COMP_ARCSPEED_ARCSPEED 0
#define _UI_COMP_ARCSPEED_NUM 1
lv_obj_t * ui_Arcspeed_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
