// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: scclighttest

#include "ui.h"

void ui_comp_Image1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Image2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Arcspeed_create_hook(lv_obj_t * comp)
{
}
